name: PowerFulPickaxe
version: '1.0-SNAPSHOT'
main: me.hazem.powerfulpickaxe.PowerFulPickaxe
api-version: 1.19
commands:
  setminedblocks:
    description: sets MinedBlocks on Ultimate Pickaxe PersistentDataContainer
  settier:
    description: sets MiningTier on Ultimate Pickaxe PersistentDataContainer